<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Shared.Abstractions\Shared.Abstractions.csproj" />
      <ProjectReference Include="..\..\..\Shared\Shared.Application\Shared.Application.csproj" />
      <ProjectReference Include="..\..\..\Shared\Shared.EntityFramework\Shared.EntityFramework.csproj" />
      <ProjectReference Include="..\..\Catalog\Catalog.Contracts\Catalog.Contracts.csproj" />
      <ProjectReference Include="..\Order.Contracts\Order.Contracts.csproj" />
    </ItemGroup>

</Project>
