version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: shop_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ShopDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - shop-network

  opensearch:
    image: opensearchproject/opensearch:3.8.0
    container_name: shop_opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - shop-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.8.0
    container_name: shop_opensearch_dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    networks:
      - shop-network

  rabbitmq:
    image: rabbitmq:4.3.5-management
    container_name: shop_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shop-network

  seq:
    image: datalust/seq:2026.1
    container_name: shop_seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=Password123!
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    networks:
      - shop-network

volumes:
  postgres_data:
  opensearch_data:
  rabbitmq_data:
  seq_data:

networks:
  shop-network:
    driver: bridge