version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: shop_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ShopDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  opensearch:
    image: opensearchproject/opensearch:3.8.0
    container_name: shop_opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.8.0
    container_name: shop_opensearch_dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      - opensearch

volumes:
  postgres_data:
  opensearch_data: